Repository Netflix/metacat, pull requests merged in 2018-06, with the labels that each got.

#263 Fix intermittent build errors because of docker processes exceeding instance resources.
  metacat-functional-tests/metacat-test-cluster/datastores/mysql/docker-entrypoint-initdb.d/sakila-db/sakila-data.sql
  metacat-functional-tests/metacat-test-cluster/datastores/mysql/docker-entrypoint-initdb.d/sakila-db/sakila.mwb
  metacat-functional-tests/metacat-test-cluster/docker-compose.yml
Labels: bug

#264 Add setTags() api in tagController
  gradle.properties
  metacat-client/src/main/java/com/netflix/metacat/client/api/TagV1.java
  metacat-common-server/src/main/java/com/netflix/metacat/common/server/connectors/exception/AlreadyExistsException.java
  metacat-common-server/src/main/java/com/netflix/metacat/common/server/usermetadata/TagService.java
  metacat-common/src/main/java/com/netflix/metacat/common/QualifiedName.java
  metacat-common/src/main/java/com/netflix/metacat/common/dto/TagCreateRequestDto.java
  metacat-common/src/main/java/com/netflix/metacat/common/dto/TagRemoveRequestDto.java
  metacat-functional-tests/metacat-test-cluster/datastores/cassandra/init.cql
  metacat-functional-tests/metacat-test-cluster/docker-compose.yml
  metacat-functional-tests/metacat-test-cluster/etc-metacat/catalog/cassandra-310.properties
  metacat-functional-tests/metacat-test-cluster/etc-metacat/catalog/druid-test.properties
  metacat-functional-tests/src/functionalTest/groovy/com/netflix/metacat/MetacatFunctionalSpec.groovy
  metacat-functional-tests/src/functionalTest/groovy/com/netflix/metacat/MetacatSmokeSpec.groovy
  metacat-functional-tests/src/functionalTest/groovy/com/netflix/metacat/TestCatalogs.groovy
  metacat-main/src/main/java/com/netflix/metacat/main/api/v1/TagController.java
  metacat-main/src/main/java/com/netflix/metacat/main/services/impl/TableServiceImpl.java
  metacat-metadata-mysql/src/main/java/com/netflix/metacat/metadata/mysql/MySqlTagService.java
  scripts/start_metacat_test_cluster.sh
Labels: bug, enhancement

#265 Fixed issue where thrift methods returning partitions were returning partitions with partition values escaped.
  metacat-functional-tests/src/functionalTest/groovy/com/netflix/metacat/MetacatSmokeThriftSpec.groovy
  metacat-thrift/src/main/java/com/netflix/metacat/thrift/CatalogThriftHiveMetastore.java
  metacat-thrift/src/main/java/com/netflix/metacat/thrift/HiveConvertersImpl.java
  metacat-thrift/src/test/groovy/com/netflix/metacat/thrift/HiveConvertersSpec.groovy
Labels: bug

#268 Fixing the issues in partition add with delete column as empty
  metacat-main/src/main/java/com/netflix/metacat/main/services/notifications/sns/SNSNotificationPartitionAddMsg.java
  metacat-main/src/main/java/com/netflix/metacat/main/services/notifications/sns/SNSNotificationServiceUtil.java
  metacat-main/src/test/groovy/com/netflix/metacat/main/services/notifications/sns/SNSNotificationServiceUtilSpec.groovy
Labels: bug

#270 Setting timeouts for queries reading hive partitions.
  metacat-connector-hive/src/main/java/com/netflix/metacat/connector/hive/configs/HiveConnectorClientConfig.java
  metacat-connector-hive/src/main/java/com/netflix/metacat/connector/hive/sql/DirectSqlGetPartition.java
  metacat-connector-hive/src/test/groovy/com/netflix/metacat/connector/hive/configs/HiveConnectorClientConfigSpec.groovy
Labels: enhancement
