Repository Netflix/metacat, pull requests merged in 2018-05, with the labels that each got.

#254 Fixing the table listing in Snowflakes connector.
  metacat-connector-jdbc/src/main/java/com/netflix/metacat/connector/jdbc/services/JdbcConnectorTableService.java
  metacat-connector-snowflake/src/main/java/com/netflix/metacat/connector/snowflake/SnowflakeConnectorModule.java
  metacat-connector-snowflake/src/main/java/com/netflix/metacat/connector/snowflake/SnowflakeConnectorTableService.java
  metacat-connector-snowflake/src/test/groovy/com/netflix/metacat/connector/snowflake/SnowflakeConnectorTableServiceSpec.groovy
Labels: enhancement

#255 Fixing table create to merge with existing metadata.
  metacat-functional-tests/metacat-test-cluster/docker-compose.yml
  metacat-functional-tests/src/functionalTest/groovy/com/netflix/metacat/MetacatSmokeSpec.groovy
  metacat-main/src/main/java/com/netflix/metacat/main/services/impl/TableServiceImpl.java
Labels: bug

#256 Fixing other apis in snowflake connector.
  metacat-connector-jdbc/src/main/java/com/netflix/metacat/connector/jdbc/services/JdbcConnectorTableService.java
  metacat-connector-snowflake/src/main/java/com/netflix/metacat/connector/snowflake/SnowflakeConnectorTableService.java
  metacat-connector-snowflake/src/test/groovy/com/netflix/metacat/connector/snowflake/SnowflakeConnectorTableServiceSpec.groovy
Labels: bug, enhancement

#257 Reverting back the table exists change for snowflake-connector.
  metacat-connector-jdbc/src/main/java/com/netflix/metacat/connector/jdbc/services/JdbcConnectorTableService.java
  metacat-connector-snowflake/src/main/java/com/netflix/metacat/connector/snowflake/SnowflakeConnectorTableService.java
Labels: bug

#258 Implement few thrift APIs
  build.gradle
  metacat-common-server/src/main/java/com/netflix/metacat/common/server/api/v1/MetacatV1.java
  metacat-common/src/main/java/com/netflix/metacat/common/dto/DatabaseCreateRequestDto.java
  metacat-functional-tests/src/functionalTest/groovy/com/netflix/metacat/MetacatFunctionalSpec.groovy
  metacat-functional-tests/src/functionalTest/groovy/com/netflix/metacat/MetacatSmokeSpec.groovy
  metacat-functional-tests/src/functionalTest/groovy/com/netflix/metacat/MetacatSmokeThriftSpec.groovy
  metacat-functional-tests/src/functionalTest/groovy/com/netflix/metacat/MetacatThriftFunctionalSpec.groovy
  metacat-main/src/main/java/com/netflix/metacat/main/api/v1/MetacatController.java
  metacat-thrift/build.gradle
  metacat-thrift/src/main/java/com/netflix/metacat/thrift/CatalogThriftHiveMetastore.java
  metacat-thrift/src/test/groovy/com/netflix/metacat/thrift/CatalogThriftHiveMetastoreSpec.groovy
Labels: enhancement

#259 Fix intermittent build errors because of docker processes exceeding instance resources.
  buildViaTravis.sh
  metacat-functional-tests/metacat-test-cluster/datastores/mysql/docker-entrypoint-initdb.d/world.sql
  metacat-functional-tests/metacat-test-cluster/datastores/postgres/docker-entrypoint-initdb.d/pagila-0.10.1/README
  metacat-functional-tests/metacat-test-cluster/datastores/postgres/docker-entrypoint-initdb.d/pagila-0.10.1/pagila-data.sql
  metacat-functional-tests/metacat-test-cluster/datastores/postgres/docker-entrypoint-initdb.d/pagila-0.10.1/pagila-insert-data.sql
  metacat-functional-tests/metacat-test-cluster/datastores/postgres/docker-entrypoint-initdb.d/pagila-0.10.1/pagila-schema.sql
  metacat-functional-tests/metacat-test-cluster/datastores/postgres/docker-entrypoint-initdb.d/world/world.sql
Labels: bug

#261 Fixed issue with dropping a bucketed table.
  metacat-connector-hive/src/main/java/com/netflix/metacat/connector/hive/sql/DirectSqlSavePartition.java
  metacat-connector-hive/src/test/groovy/com/netflix/metacat/connector/hive/sql/DirectSqlSavePartitionSpec.groovy
Labels: bug

#262 On Hive table rename, convert a managed table to an external table.
  metacat-connector-hive/src/main/java/com/netflix/metacat/connector/hive/HiveConnectorTableService.java
  metacat-connector-hive/src/main/java/com/netflix/metacat/connector/hive/util/HiveConfigConstants.java
  metacat-connector-hive/src/test/groovy/com/netflix/metacat/connector/hive/HiveConnectorTableSpec.groovy
  metacat-functional-tests/src/functionalTest/groovy/com/netflix/metacat/MetacatSmokeSpec.groovy
Labels: enhancement
